### ISSUE TITLE
Update to latest FontAwesome

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux-theme#53]
FontAwesome 5.x release is out. They have changed their naming convention so we'll need to ensure that components that reference FA icons get updated as well.

**Comment by Blackbaud-BobbyEarl** [comment]
I hoped https://github.com/blackbaud/skyux-theme/pull/65 would be able to introduce Font Awesome 5, while remaining 100% backwards compatible.  Through the course of that PR, I am now confident in saying that is not possible.

### Discovery
Font Awesome 5 introduced several documented breaking changes.  Those changes include the CSS class names, the `font-family` name, and in a few cases, the actual Unicode characters.  

- The CSS class names is easy to fix as Font Awesome also released a `v4-shims.css` file to bridge this gap.
- The `font-family` is unfortunately not solvable (in a non-breaking way).  I can duplicate the original FontAwesome `font-family` and have it point to the new fonts; however, I wouldn't be able to map the original unicode characters to their new home since the fonts have been split into Solid, Regular, and Brands.
- Certain unicode characters have been changed, which is another example of why I can't introduce this without a breaking change.  For example, the `fa-arrows` class is Unicode character `f047` in [Font Awesome 4](https://fontawesome.com/v4.7.0/icon/arrows).  

In Font Awesome 5 however, that specific Unicode character has been moved to the paid-only version.  It's free replacement is Unicode character `f0b2` with class name `arrows-alt`.  There is a team using this icon by its unicode today.
- https://fontawesome.com/icons/arrows?style=solid
- https://fontawesome.com/icons/arrows-alt?style=solid

### Prioritization

We have decided to de-prioritize this work based on a few factors:

- The in ability to introduce v5 with 100% confidence that no breaking changes are introduced.
- The amount of work necessary to upgrade our components to support v5.

### Going Forward

We also talked through a few approaches on how we could introduce this as an opt-in technique.  Both a somewhat complex, but I wanted to mention them when we're available to pick this back up.

- Create a `@skyux-sdk/builder` plugin which alters the `style-loader` and `sky.css` files.  It could replace the lines import v4 / checking for v4 font with lines that are importing v5 and checking for a v5 font.
- Create a FontAwesomeVersionProvider.  This is useful as it keeps `@skyux/theme` from having to know about `SkyAppConfig`.  Build could instead choose to inject the right provider based on `@skyux/config` property.

**Comment by Blackbaud-SteveBrush** [comment]
Closing since we decided to go with a custom icon set, see: https://github.com/blackbaud/skyux-theme/pull/102
